// Autogenerated AST node
package pers.xia.jpython.ast;
import java.io.DataOutputStream;
import java.io.IOException;

public class Compare extends exprType {
    public exprType left;
    public cmpopType ops;
    public exprType right;

    public Compare(exprType left, cmpopType ops,
                   exprType right, int lineno, int col_offset) {
        this.left = left;
        this.ops = ops;
        this.right = right;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "Compare";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitCompare(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
