// Autogenerated AST node
package pers.xia.jpython.ast;
import java.io.DataOutputStream;
import java.io.IOException;

public class Name extends exprType {

    public String id;
    public expr_contextType ctx;

    public Name(String id, expr_contextType ctx)
    {
        this.id = id;
        this.ctx = ctx;
        this.lineno = lineno;
        this.col_offset = col_offset;
    }

    public String toString() {
        return "Name";
    }

    public void pickle(DataOutputStream ostream) throws IOException {
    }

    public Object accept(VisitorIF visitor) throws Exception {
        return visitor.visitName(this);
    }
    public String getId() {
        return id;
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
