// Autogenerated AST node
package pers.xia.jpython.ast;

public enum OperatorType {
    UNDEFINED,
    Add,
    Sub,
    Mult,
    MatMult,
    Div,
    Mod,
    Pow,
    LShift,
    RShift,
    BitOr,
    BitXor,
    BitAnd,
    FloorDiv,
}
